//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibleMyraUI {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccessibilityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessibilityResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibleMyraUI.AccessibilityResources", typeof(AccessibilityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Button: {0}.
        /// </summary>
        internal static string Button_Focus {
            get {
                return ResourceManager.GetString("Button_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}, checked.
        /// </summary>
        internal static string CheckBox_Checked {
            get {
                return ResourceManager.GetString("CheckBox_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}, unchecked.
        /// </summary>
        internal static string CheckBox_Unchecked {
            get {
                return ResourceManager.GetString("CheckBox_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dropdown list.
        /// </summary>
        internal static string ComboBox_Focus {
            get {
                return ResourceManager.GetString("ComboBox_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dropdown list, selected: {0}.
        /// </summary>
        internal static string ComboBox_Selected {
            get {
                return ResourceManager.GetString("ComboBox_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}.
        /// </summary>
        internal static string Label_Focus {
            get {
                return ResourceManager.GetString("Label_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List.
        /// </summary>
        internal static string ListBox_Focus {
            get {
                return ResourceManager.GetString("ListBox_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List, no selection.
        /// </summary>
        internal static string ListBox_NoSelection {
            get {
                return ResourceManager.GetString("ListBox_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List, selected: {0}.
        /// </summary>
        internal static string ListBox_Selected {
            get {
                return ResourceManager.GetString("ListBox_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option {0}, selected.
        /// </summary>
        internal static string RadioButton_Selected {
            get {
                return ResourceManager.GetString("RadioButton_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option {0}, not selected.
        /// </summary>
        internal static string RadioButton_Unselected {
            get {
                return ResourceManager.GetString("RadioButton_Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value: {0} percent.
        /// </summary>
        internal static string Slider_Value {
            get {
                return ResourceManager.GetString("Slider_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab {0} selected.
        /// </summary>
        internal static string Tab_Selected {
            get {
                return ResourceManager.GetString("Tab_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unnamed tab.
        /// </summary>
        internal static string Tab_Unnamed {
            get {
                return ResourceManager.GetString("Tab_Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty text box.
        /// </summary>
        internal static string TextBox_Empty {
            get {
                return ResourceManager.GetString("TextBox_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text box: {0}.
        /// </summary>
        internal static string TextBox_Focus {
            get {
                return ResourceManager.GetString("TextBox_Focus", resourceCulture);
            }
        }
    }
}
