name: Release to GitHub

on:
  push:
    tags:
      - 'v*'  # Déclenchement sur les tags versionnés (ex: v1.0.0)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV

    - name: Setup Wine
      run: |
        sudo apt update
        sudo apt install wine64 p7zip-full curl
        wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/78636f8056fa981584e3a2a3e0f22e2efbc43ef8/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh

    - name: Build Windows
      run: dotnet publish Platforms/DesktopGL -r win-x64 -c Release --self-contained --output artifacts/windows

    - name: Build macOS
      run: dotnet publish Platforms/DesktopGL -r osx-x64 -c Release --self-contained --output artifacts/macos

    - name: Build Linux
      run: dotnet publish Platforms/DesktopGL -r linux-x64 -c Release --self-contained --output artifacts/linux

    - name: Package Builds
      run: |
        cd artifacts
        zip -r windows.zip windows
        zip -r macos.zip macos
        zip -r linux.zip linux

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/windows.zip
          artifacts/macos.zip
          artifacts/linux.zip
        name: Release ${{ env.TAGVERSION }}
        tag_name: v${{ env.TAGVERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
